'use client'
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react'
import {KeyRound,Plus,ShieldCheck,UserRoundCheck,UserRoundX} from 'lucide-react'
import Protected from '@/components/Protected'
import {createClient} from '@/lib/supabase/client'
import {roleLabels} from '@/lib/constants'

type UserRow={id:string;email:string;full_name:string;role:string;active:boolean;must_change_password:boolean;created_at:string}
const roles=['admin','warehouse_manager','sale_support','counter','viewer']

export default function Users(){
 const[rows,setRows]=useState<UserRow[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const[username,setUsername]=useState('');const[fullName,setFullName]=useState('');const[role,setRole]=useState('counter');const[password,setPassword]=useState('1234');const supabase=useMemo(()=>createClient(),[])
 const api=useCallback(async(method:string,body?:unknown)=>{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Session หมดอายุ กรุณา Login ใหม่');const response=await fetch('/api/admin/users',{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||'เกิดข้อผิดพลาด');return result},[supabase])
 const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await api('GET');setRows(result.users||[])}catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ')}finally{setLoading(false)}},[api])
 useEffect(()=>{load()},[load])
 async function createUser(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{await api('POST',{username,fullName,role,password});setMessage(`สร้างผู้ใช้ ${username} เรียบร้อยแล้ว`);setUsername('');setFullName('');setRole('counter');setPassword('1234');await load()}catch(e){setError(e instanceof Error?e.message:'สร้างผู้ใช้ไม่สำเร็จ')}finally{setBusy(false)}}
 async function updateUser(row:UserRow,changes:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{await api('PATCH',{id:row.id,...changes});setMessage('บันทึกการเปลี่ยนแปลงแล้ว');await load()}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่สำเร็จ')}finally{setBusy(false)}}
 async function resetPassword(row:UserRow){const value=window.prompt(`ตั้งรหัสผ่านชั่วคราวสำหรับ ${row.email.split('@')[0]}`,'1234');if(!value)return;await updateUser(row,{password:value,mustChangePassword:true})}
 return <Protected>
  <div className="page-head"><div><h1>ผู้ใช้งานและสิทธิ์</h1><p>Admin เพิ่มผู้ใช้ กำหนดบทบาท รีเซ็ตรหัสผ่าน และระงับบัญชีได้จากหน้านี้</p></div></div>
  {error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}{message&&<div className="success-box" style={{marginBottom:12}}>{message}</div>}
  <div className="card" style={{marginBottom:16}}><div className="card-title"><h2>เพิ่มผู้ใช้งาน</h2><Plus size={18} className="muted"/></div><form className="filters" style={{gridTemplateColumns:'repeat(4,minmax(150px,1fr)) auto',marginBottom:0}} onSubmit={createUser}><div className="field"><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="เช่น counter01" required/></div><div className="field"><label>ชื่อ-นามสกุล</label><input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="ชื่อผู้ใช้งาน"/></div><div className="field"><label>บทบาท</label><select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(x=><option key={x} value={x}>{roleLabels[x]}</option>)}</select></div><div className="field"><label>รหัสผ่านชั่วคราว</label><input value={password} onChange={e=>setPassword(e.target.value)} minLength={4} required/></div><div className="field"><label>&nbsp;</label><button className="btn primary" disabled={busy}><Plus size={15}/>เพิ่มผู้ใช้</button></div></form><div className="notice" style={{marginTop:13}}>สามารถใช้รหัสชั่วคราว 1234 ได้ ผู้ใช้จะเห็นคำเตือนให้เปลี่ยนรหัสผ่านหลังเข้าสู่ระบบ</div></div>
  <div className="grid kpi-grid"><UserKpi label="ผู้ใช้ทั้งหมด" value={rows.length}/><UserKpi label="กำลังใช้งาน" value={rows.filter(x=>x.active).length} tone="good"/><UserKpi label="Admin" value={rows.filter(x=>x.role==='admin'&&x.active).length}/><UserKpi label="ต้องเปลี่ยนรหัสผ่าน" value={rows.filter(x=>x.must_change_password).length} tone="warn"/></div>
  <div className="card"><div className="table-wrap"><table className="table"><thead><tr><th>ชื่อผู้ใช้</th><th>ชื่อ</th><th>บทบาท</th><th>รหัสผ่าน</th><th>สถานะ</th><th>สร้างเมื่อ</th><th>จัดการ</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="empty">กำลังโหลด...</td></tr>:rows.map(row=><tr key={row.id}><td><strong>{row.email.split('@')[0]}</strong><div className="muted">{row.email}</div></td><td>{row.full_name||'-'}</td><td><select value={row.role} disabled={busy} onChange={e=>updateUser(row,{role:e.target.value})}>{roles.map(x=><option key={x} value={x}>{roleLabels[x]}</option>)}</select></td><td><span className={`badge ${row.must_change_password?'warn':'ok'}`}>{row.must_change_password?'รหัสชั่วคราว':'เปลี่ยนแล้ว'}</span></td><td><span className={`badge ${row.active?'ok':'bad'}`}>{row.active?'ใช้งาน':'ระงับ'}</span></td><td>{new Date(row.created_at).toLocaleDateString('th-TH')}</td><td><div className="actions"><button className="btn small secondary" disabled={busy} onClick={()=>resetPassword(row)}><KeyRound size={13}/>รีเซ็ตรหัส</button><button className={row.active?'btn small danger':'btn small success'} disabled={busy} onClick={()=>updateUser(row,{active:!row.active})}>{row.active?<><UserRoundX size={13}/>ระงับ</>:<><UserRoundCheck size={13}/>เปิดใช้</>}</button></div></td></tr>)}</tbody></table></div></div>
 </Protected>
}
function UserKpi({label,value,tone='' }:{label:string;value:number;tone?:string}){return <div className={`kpi-card ${tone}`}><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="kpi-sub"><ShieldCheck size={12}/> บัญชีในระบบ</div></div>}
