'use client'
import {useEffect,useMemo,useState} from 'react'
import {Download,FileBarChart2,Printer} from 'lucide-react'
import Protected from '@/components/Protected'
import {createClient} from '@/lib/supabase/client'
import {conditionLabel,statusLabel} from '@/lib/constants'
import {exportXlsx} from '@/lib/export'
import type {CountRound} from '@/lib/types'

type Variance={round_id:string;sku:string;product_name:string;brand:string;category:string;unit:string;warehouse_name:string;location_code:string;location_name:string;condition:string;system_quantity:number;counted_quantity:number;difference:number}
type ReportRow={label:string;lines:number;system:number;counted:number;short:number;over:number;difference:number}

export default function Reports(){
 const s=useMemo(()=>createClient(),[]);const[rounds,setRounds]=useState<CountRound[]>([]);const[roundId,setRoundId]=useState('');const[data,setData]=useState<Variance[]>([]);const[tab,setTab]=useState<'brand'|'location'|'condition'|'variance'>('brand');const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 async function loadRounds(){const{data}=await s.from('count_rounds').select('*,warehouses(code,name)').order('created_at',{ascending:false});const rows=(data||[]) as CountRound[];setRounds(rows);const requested=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('round')||'':'';if(requested&&rows.some(x=>x.id===requested))setRoundId(requested);else if(!roundId&&rows[0])setRoundId(rows[0].id)}
 async function load(){if(!roundId){setData([]);setLoading(false);return}setLoading(true);const{data,error}=await s.from('v_round_variance').select('*').eq('round_id',roundId).order('brand').order('sku');if(error)setError(error.message);setData((data||[]) as Variance[]);setLoading(false)}
 useEffect(()=>{loadRounds()},[]);useEffect(()=>{load()},[roundId])
 const report=tab==='brand'?group(data,x=>x.brand||'ไม่ระบุแบรนด์'):tab==='location'?group(data,x=>`${x.warehouse_name} / ${x.location_code} ${x.location_name}`):tab==='condition'?group(data,x=>conditionLabel(x.condition)):[]
 const variances=data.filter(x=>Number(x.difference)!==0).sort((a,b)=>Math.abs(Number(b.difference))-Math.abs(Number(a.difference)))
 const current=rounds.find(x=>x.id===roundId)
 async function exportReport(){if(tab==='variance')await exportXlsx(variances.map(x=>({'SKU':x.sku,'สินค้า':x.product_name,'แบรนด์':x.brand,'คลัง':x.warehouse_name,'โลเคชั่น':`${x.location_code} ${x.location_name}`,'สภาพ':conditionLabel(x.condition),'ยอดตามระบบ':x.system_quantity,'นับจริง':x.counted_quantity,'ผลต่าง':x.difference})),'MBC_Variance_Report.xlsx','ผลต่าง');else await exportXlsx(report.map(x=>({'รายการ':x.label,'จำนวนบรรทัด':x.lines,'ยอดตามระบบ':x.system,'ยอดนับจริง':x.counted,'จำนวนขาด':x.short,'จำนวนเกิน':x.over,'ผลต่างสุทธิ':x.difference})),'MBC_Inventory_Report.xlsx','สรุปรายงาน')}
 return <Protected>
  <div className="page-head"><div><h1>รายงาน</h1><p>สรุปผลตรวจนับแยกตามแบรนด์ คลัง/โลเคชั่น สภาพสินค้า และรายการผิดปกติ</p></div><div className="actions"><button className="btn outline" onClick={()=>window.print()}><Printer size={15}/>พิมพ์</button><button className="btn primary" onClick={exportReport} disabled={!data.length}><Download size={15}/>ส่งออก Excel</button></div></div>
  {error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}
  <div className="card" style={{marginBottom:15}}><div className="filters" style={{gridTemplateColumns:'minmax(250px,2fr) 1fr 1fr',marginBottom:0}}><div className="field"><label>รอบตรวจนับ</label><select value={roundId} onChange={e=>setRoundId(e.target.value)}><option value="">เลือกรอบ</option>{rounds.map(r=><option key={r.id} value={r.id}>{r.code} · {r.name}</option>)}</select></div><div className="field"><label>สถานะรอบ</label><input value={current?statusLabel(current.status):'-'} disabled/></div><div className="field"><label>คลัง</label><input value={current?.warehouses?.name||'-'} disabled/></div></div></div>
  <div className="grid kpi-grid"><Kpi label="รายการทั้งหมด" value={data.length}/><Kpi label="จำนวนตามระบบ" value={data.reduce((n,x)=>n+Number(x.system_quantity),0)}/><Kpi label="จำนวนที่นับจริง" value={data.reduce((n,x)=>n+Number(x.counted_quantity),0)} tone="good"/><Kpi label="รายการมีผลต่าง" value={variances.length} tone={variances.length?'warn':''}/></div>
  <div className="tabs"><button className={`tab ${tab==='brand'?'active':''}`} onClick={()=>setTab('brand')}>แยกตามแบรนด์</button><button className={`tab ${tab==='location'?'active':''}`} onClick={()=>setTab('location')}>แยกตามคลัง/โลเคชั่น</button><button className={`tab ${tab==='condition'?'active':''}`} onClick={()=>setTab('condition')}>แยกตามสภาพ</button><button className={`tab ${tab==='variance'?'active':''}`} onClick={()=>setTab('variance')}>สินค้าขาด/เกิน</button></div>
  <div className="card"><div className="card-title"><h2>{tab==='brand'?'สรุปตามแบรนด์':tab==='location'?'สรุปตามคลังและโลเคชั่น':tab==='condition'?'สรุปตามสภาพสินค้า':'รายละเอียดสินค้าที่มีผลต่าง'}</h2><FileBarChart2 size={18} className="muted"/></div>{loading?<div className="empty">กำลังประมวลผลรายงาน...</div>:tab==='variance'?<div className="table-wrap"><table className="table"><thead><tr><th>SKU / สินค้า</th><th>แบรนด์</th><th>คลัง / โลเคชั่น</th><th>สภาพ</th><th>ตามระบบ</th><th>นับจริง</th><th>ผลต่าง</th></tr></thead><tbody>{variances.length?variances.map((x,i)=><tr key={`${x.sku}-${x.location_code}-${x.condition}-${i}`}><td className="wrap"><strong>{x.sku}</strong><div className="muted">{x.product_name}</div></td><td>{x.brand||'-'}</td><td>{x.warehouse_name}<div className="muted">{x.location_code} · {x.location_name}</div></td><td>{conditionLabel(x.condition)}</td><td>{Number(x.system_quantity).toLocaleString()}</td><td>{Number(x.counted_quantity).toLocaleString()}</td><td className={x.difference>0?'diff-pos':'diff-neg'}>{x.difference>0?'+':''}{Number(x.difference).toLocaleString()}</td></tr>):<tr><td colSpan={7} className="empty">ไม่มีผลต่างในรอบนี้</td></tr>}</tbody></table></div>:<div className="table-wrap"><table className="table"><thead><tr><th>รายการ</th><th>จำนวนบรรทัด</th><th>ยอดตามระบบ</th><th>นับจริง</th><th>จำนวนขาด</th><th>จำนวนเกิน</th><th>ผลต่างสุทธิ</th></tr></thead><tbody>{report.length?report.map(x=><tr key={x.label}><td className="wrap"><strong>{x.label}</strong></td><td>{x.lines.toLocaleString()}</td><td>{x.system.toLocaleString()}</td><td>{x.counted.toLocaleString()}</td><td className="diff-neg">{x.short.toLocaleString()}</td><td className="diff-pos">{x.over.toLocaleString()}</td><td className={x.difference>0?'diff-pos':x.difference<0?'diff-neg':'diff-zero'}>{x.difference>0?'+':''}{x.difference.toLocaleString()}</td></tr>):<tr><td colSpan={7} className="empty">ยังไม่มีข้อมูลรายงาน</td></tr>}</tbody></table></div>}</div>
 </Protected>
}
function group(data:Variance[],key:(x:Variance)=>string){const map=new Map<string,ReportRow>();for(const x of data){const label=key(x);const row=map.get(label)||{label,lines:0,system:0,counted:0,short:0,over:0,difference:0};row.lines++;row.system+=Number(x.system_quantity);row.counted+=Number(x.counted_quantity);row.difference+=Number(x.difference);if(x.difference<0)row.short+=Math.abs(Number(x.difference));if(x.difference>0)row.over+=Number(x.difference);map.set(label,row)}return [...map.values()].sort((a,b)=>b.counted-a.counted)}
function Kpi({label,value,tone='' }:{label:string;value:number;tone?:string}){return <div className={`kpi-card ${tone}`}><div className="kpi-label">{label}</div><div className="kpi-value">{value.toLocaleString()}</div><div className="kpi-sub">รอบที่เลือก</div></div>}
