'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {Building2,Edit3,MapPin,Plus,Printer,QrCode,X} from 'lucide-react'
import {QRCodeSVG} from 'qrcode.react'
import Protected from '@/components/Protected'
import {createClient} from '@/lib/supabase/client'
import {conditionLabel,conditionOptions} from '@/lib/constants'
import {useProfile} from '@/lib/useProfile'
import type {Location,StockCondition,Warehouse} from '@/lib/types'

const emptyWh={id:'',code:'',name:'',description:'',address:'',active:true}
const emptyLoc={id:'',warehouse_id:'',code:'',name:'',zone:'',default_condition:'good' as StockCondition,notes:'',active:true,scan_code:''}

export default function Locations(){
 const s=useMemo(()=>createClient(),[]);const{profile}=useProfile();const canManage=!!profile&&['admin','warehouse_manager','sale_support'].includes(profile.role)
 const[warehouses,setWarehouses]=useState<Warehouse[]>([]);const[locations,setLocations]=useState<Location[]>([]);const[selected,setSelected]=useState('');const[whOpen,setWhOpen]=useState(false);const[locOpen,setLocOpen]=useState(false);const[qrLoc,setQrLoc]=useState<Location|null>(null);const[whForm,setWhForm]=useState(emptyWh);const[locForm,setLocForm]=useState(emptyLoc);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('')
 async function load(){const[{data:w,error:e1},{data:l,error:e2}]=await Promise.all([s.from('warehouses').select('*').order('code'),s.from('locations').select('*,warehouses(code,name)').order('code')]);if(e1||e2)setError(e1?.message||e2?.message||'โหลดข้อมูลไม่สำเร็จ');const ws=(w||[]) as Warehouse[];setWarehouses(ws);setLocations((l||[]) as Location[]);if(!selected&&ws[0])setSelected(ws[0].id)}
 useEffect(()=>{load()},[])
 function addWarehouse(){setWhForm(emptyWh);setWhOpen(true)}function editWarehouse(w:Warehouse){setWhForm({...w});setWhOpen(true)}
 function addLocation(){setLocForm({...emptyLoc,warehouse_id:selected});setLocOpen(true)}function editLocation(l:Location){setLocForm({...l,scan_code:l.scan_code||''});setLocOpen(true)}
 async function saveWarehouse(e:FormEvent){e.preventDefault();setBusy(true);const payload={code:whForm.code.trim().toUpperCase(),name:whForm.name.trim(),description:whForm.description.trim(),address:whForm.address.trim(),active:whForm.active,updated_at:new Date().toISOString()};const result=whForm.id?await s.from('warehouses').update(payload).eq('id',whForm.id):await s.from('warehouses').insert(payload);if(result.error)setError(result.error.message);else{setMessage('บันทึกคลังสินค้าแล้ว');setWhOpen(false);load()}setBusy(false)}
 async function saveLocation(e:FormEvent){e.preventDefault();setBusy(true);const payload={warehouse_id:locForm.warehouse_id,code:locForm.code.trim().toUpperCase(),name:locForm.name.trim(),zone:locForm.zone.trim(),default_condition:locForm.default_condition,notes:locForm.notes.trim(),active:locForm.active,updated_at:new Date().toISOString()};if(locForm.id){const{error}=await s.from('locations').update({...payload,scan_code:locForm.scan_code||`LOC:${locForm.id}`}).eq('id',locForm.id);if(error)setError(error.message);else{setMessage('บันทึกโลเคชั่นแล้ว');setLocOpen(false);load()}}else{const{data,error}=await s.from('locations').insert(payload).select('id').single();if(error)setError(error.message);else{await s.from('locations').update({scan_code:`LOC:${data.id}`}).eq('id',data.id);setMessage('สร้างโลเคชั่นและรหัสสแกนแล้ว');setLocOpen(false);load()}}setBusy(false)}
 const current=warehouses.find(x=>x.id===selected);const currentLocations=locations.filter(x=>x.warehouse_id===selected)
 function printQr(){const content=document.getElementById('location-qr-print')?.innerHTML;if(!content)return;const win=window.open('','_blank','width=520,height=650');if(!win)return;win.document.write(`<html><head><title>Location QR</title><style>body{font-family:Arial,sans-serif;display:grid;place-items:center;padding:30px;text-align:center}svg{max-width:260px}h2{margin:12px 0 4px}.muted{color:#667085}code{display:block;margin-top:8px;font-size:11px}</style></head><body><div>${content}</div><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close()}
 return <Protected>
  <div className="page-head"><div><h1>คลังและโลเคชั่น</h1><p>แยกพื้นที่จัดเก็บ เช่น ของปกติ กล่องบุบ เคลม รอตรวจสอบ และพื้นที่อื่น</p></div>{canManage&&<div className="actions"><button className="btn outline" onClick={addWarehouse}><Building2 size={15}/>เพิ่มคลัง</button><button className="btn primary" onClick={addLocation} disabled={!selected}><Plus size={15}/>เพิ่มโลเคชั่น</button></div>}</div>
  {error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}{message&&<div className="success-box" style={{marginBottom:12}}>{message}</div>}
  <div className="split-layout"><div className="card"><div className="card-title"><h2>โครงสร้างคลัง</h2><span className="badge">{warehouses.length} คลัง</span></div><div className="warehouse-list">{warehouses.map(w=><div key={w.id} className={`warehouse-card ${selected===w.id?'active':''}`} onClick={()=>setSelected(w.id)}><div style={{display:'flex',alignItems:'center',gap:10}}><div className="location-code"><Building2 size={16}/></div><div style={{flex:1}}><h3>{w.code} · {w.name}</h3><p>{locations.filter(l=>l.warehouse_id===w.id).length} โลเคชั่น · {w.active?'เปิดใช้งาน':'ปิดใช้งาน'}</p></div>{canManage&&<button className="icon-button" onClick={e=>{e.stopPropagation();editWarehouse(w)}}><Edit3 size={14}/></button>}</div></div>)}</div></div>
   <div className="card"><div className="card-title"><div><h2>{current?`${current.code} · ${current.name}`:'เลือกคลังสินค้า'}</h2>{current&&<div className="muted" style={{fontSize:11,marginTop:4}}>{current.description||'ไม่มีรายละเอียดเพิ่มเติม'}</div>}</div><MapPin size={18} className="muted"/></div>{currentLocations.length?currentLocations.map(l=><div className="location-row" key={l.id}><div className="location-code">{l.code}</div><div className="location-copy"><strong>{l.name}</strong><span>{l.zone?`โซน ${l.zone} · `:''}{conditionLabel(l.default_condition)} · {l.active?'เปิดใช้งาน':'ปิดใช้งาน'}</span></div><span className="badge dark">{conditionLabel(l.default_condition)}</span><button className="icon-button" title="QR Code" onClick={()=>setQrLoc(l)}><QrCode size={14}/></button>{canManage&&<button className="icon-button" title="แก้ไข" onClick={()=>editLocation(l)}><Edit3 size={14}/></button>}</div>):<div className="empty">คลังนี้ยังไม่มีโลเคชั่น</div>}</div>
  </div>
  {whOpen&&<div className="modal-backdrop"><form className="modal" onSubmit={saveWarehouse}><div className="modal-header"><h2>{whForm.id?'แก้ไขคลังสินค้า':'เพิ่มคลังสินค้า'}</h2><button type="button" className="icon-button" onClick={()=>setWhOpen(false)}><X size={18}/></button></div><div className="form-grid"><div className="field"><label>รหัสคลัง *</label><input value={whForm.code} onChange={e=>setWhForm({...whForm,code:e.target.value})} required/></div><div className="field"><label>ชื่อคลัง *</label><input value={whForm.name} onChange={e=>setWhForm({...whForm,name:e.target.value})} required/></div><div className="field full"><label>รายละเอียด</label><textarea value={whForm.description} onChange={e=>setWhForm({...whForm,description:e.target.value})}/></div><div className="field full"><label>ที่อยู่ / จุดสังเกต</label><textarea value={whForm.address} onChange={e=>setWhForm({...whForm,address:e.target.value})}/></div><label className="checkbox full"><input type="checkbox" checked={whForm.active} onChange={e=>setWhForm({...whForm,active:e.target.checked})}/>เปิดใช้งานคลัง</label></div><div className="modal-footer"><button type="button" className="btn outline" onClick={()=>setWhOpen(false)}>ยกเลิก</button><button className="btn primary" disabled={busy}>บันทึก</button></div></form></div>}
  {locOpen&&<div className="modal-backdrop"><form className="modal" onSubmit={saveLocation}><div className="modal-header"><h2>{locForm.id?'แก้ไขโลเคชั่น':'เพิ่มโลเคชั่น'}</h2><button type="button" className="icon-button" onClick={()=>setLocOpen(false)}><X size={18}/></button></div><div className="form-grid"><div className="field full"><label>คลังสินค้า *</label><select value={locForm.warehouse_id} onChange={e=>setLocForm({...locForm,warehouse_id:e.target.value})}>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></div><div className="field"><label>รหัสโลเคชั่น *</label><input value={locForm.code} onChange={e=>setLocForm({...locForm,code:e.target.value})} placeholder="เช่น A-01" required/></div><div className="field"><label>ชื่อโลเคชั่น *</label><input value={locForm.name} onChange={e=>setLocForm({...locForm,name:e.target.value})} placeholder="เช่น ของปกติ" required/></div><div className="field"><label>โซน / ชั้นวาง</label><input value={locForm.zone} onChange={e=>setLocForm({...locForm,zone:e.target.value})}/></div><div className="field"><label>สภาพสินค้าเริ่มต้น</label><select value={locForm.default_condition} onChange={e=>setLocForm({...locForm,default_condition:e.target.value as StockCondition})}>{conditionOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></div>{locForm.id&&<div className="field full"><label>รหัสสแกนโลเคชั่น</label><input value={locForm.scan_code} onChange={e=>setLocForm({...locForm,scan_code:e.target.value})}/></div>}<div className="field full"><label>หมายเหตุ</label><textarea value={locForm.notes} onChange={e=>setLocForm({...locForm,notes:e.target.value})}/></div><label className="checkbox full"><input type="checkbox" checked={locForm.active} onChange={e=>setLocForm({...locForm,active:e.target.checked})}/>เปิดใช้งานโลเคชั่น</label></div><div className="modal-footer"><button type="button" className="btn outline" onClick={()=>setLocOpen(false)}>ยกเลิก</button><button className="btn primary" disabled={busy}>บันทึก</button></div></form></div>}
  {qrLoc&&<div className="modal-backdrop"><div className="modal" style={{width:'min(460px,100%)'}}><div className="modal-header"><h2>QR Code โลเคชั่น</h2><button className="icon-button" onClick={()=>setQrLoc(null)}><X size={18}/></button></div><div className="qr-box" id="location-qr-print"><QRCodeSVG value={qrLoc.scan_code||`LOC:${qrLoc.id}`} size={220} level="M" includeMargin/><h2 style={{margin:'12px 0 3px'}}>{qrLoc.code} · {qrLoc.name}</h2><div className="muted">{qrLoc.warehouses?.name} · {conditionLabel(qrLoc.default_condition)}</div><code style={{marginTop:8,fontSize:10}}>{qrLoc.scan_code||`LOC:${qrLoc.id}`}</code></div><div className="modal-footer"><button className="btn outline" onClick={()=>setQrLoc(null)}>ปิด</button><button className="btn primary" onClick={printQr}><Printer size={15}/>พิมพ์ QR Code</button></div></div></div>}
 </Protected>
}
