'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {Database,KeyRound,Save,Settings2,ShieldAlert} from 'lucide-react'
import Protected from '@/components/Protected'
import {createClient} from '@/lib/supabase/client'
import {useProfile} from '@/lib/useProfile'

export default function Settings(){
 const s=useMemo(()=>createClient(),[]);const{profile,reload}=useProfile();const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[org,setOrg]=useState({name:'MBC Communications',system_name:'Inventory Count System'});const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('')
 useEffect(()=>{s.from('app_settings').select('value').eq('key','organization').maybeSingle().then(({data})=>{if(data?.value)setOrg({...org,...data.value})})},[])
 async function changePassword(e:FormEvent){e.preventDefault();setError('');setMessage('');if(password.length<8)return setError('รหัสผ่านใหม่ต้องมีอย่างน้อย 8 ตัวอักษร');if(password!==confirm)return setError('ยืนยันรหัสผ่านไม่ตรงกัน');setBusy(true);const{error:e1}=await s.auth.updateUser({password});if(e1)setError(e1.message);else{const{error:e2}=await s.rpc('complete_password_change');if(e2)setError(e2.message);else{setMessage('เปลี่ยนรหัสผ่านเรียบร้อยแล้ว');setPassword('');setConfirm('');reload()}}setBusy(false)}
 async function saveOrg(e:FormEvent){e.preventDefault();setBusy(true);setError('');const{data:{user}}=await s.auth.getUser();const{error}=await s.from('app_settings').upsert({key:'organization',value:org,updated_at:new Date().toISOString(),updated_by:user?.id||null});if(error)setError(error.message);else setMessage('บันทึกข้อมูลระบบแล้ว');setBusy(false)}
 async function resetTest(){if(!window.confirm('ยืนยันล้างรอบตรวจนับที่เป็นข้อมูลทดสอบทั้งหมด? ข้อมูลสินค้า คลัง โลเคชั่น และผู้ใช้จะยังอยู่'))return;setBusy(true);const{error}=await s.rpc('reset_test_data');if(error)setError(error.message);else setMessage('ล้างข้อมูลทดสอบเรียบร้อยแล้ว');setBusy(false)}
 return <Protected>
  <div className="page-head"><div><h1>ตั้งค่าระบบ</h1><p>ข้อมูลระบบ ความปลอดภัยบัญชี และเครื่องมือดูแลข้อมูล</p></div></div>
  {error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}{message&&<div className="success-box" style={{marginBottom:12}}>{message}</div>}
  <div className="grid two-col">
   <form className="card" onSubmit={changePassword}><div className="card-title"><h2>เปลี่ยนรหัสผ่าน</h2><KeyRound size={18} className="muted"/></div><div className="stack"><div className="field"><label>รหัสผ่านใหม่</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} autoComplete="new-password" required/></div><div className="field"><label>ยืนยันรหัสผ่านใหม่</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} autoComplete="new-password" required/></div><div className="notice">ควรใช้ตัวอักษรพิมพ์ใหญ่ พิมพ์เล็ก ตัวเลข และอักขระพิเศษร่วมกัน ห้ามใช้รหัส Admin เริ่มต้นต่อใน Production</div><button className="btn primary" disabled={busy}><Save size={15}/>บันทึกรหัสผ่านใหม่</button></div></form>
   <div className="card"><div className="card-title"><h2>สถานะบัญชี</h2><ShieldAlert size={18} className="muted"/></div><div className="location-row"><div className="location-code">ID</div><div className="location-copy"><strong>{profile?.full_name||profile?.email}</strong><span>{profile?.email}</span></div></div><div className="location-row"><div className="location-code">Role</div><div className="location-copy"><strong>{profile?.role}</strong><span>{profile?.active?'บัญชีเปิดใช้งาน':'บัญชีถูกระงับ'}</span></div></div><div className="location-row"><div className="location-code">PWD</div><div className="location-copy"><strong>{profile?.must_change_password?'ยังใช้รหัสชั่วคราว':'เปลี่ยนรหัสผ่านแล้ว'}</strong><span>สถานะความปลอดภัยของบัญชี</span></div></div></div>
  </div>
  {profile?.role==='admin'&&<><form className="card" style={{marginTop:16}} onSubmit={saveOrg}><div className="card-title"><h2>ข้อมูลระบบ</h2><Settings2 size={18} className="muted"/></div><div className="form-grid"><div className="field"><label>ชื่อองค์กร</label><input value={org.name} onChange={e=>setOrg({...org,name:e.target.value})}/></div><div className="field"><label>ชื่อระบบ</label><input value={org.system_name} onChange={e=>setOrg({...org,system_name:e.target.value})}/></div></div><div className="modal-footer"><button className="btn primary" disabled={busy}><Save size={15}/>บันทึก</button></div></form>
  <div className="card danger-zone" style={{marginTop:16}}><div className="card-title"><h2>ล้างข้อมูลทดสอบ</h2><Database size={18} color="var(--red)"/></div><p className="muted" style={{fontSize:12}}>ลบเฉพาะรอบตรวจนับที่กำหนดประเภทเป็น “ทดสอบระบบ” รวมถึง Scan Event, Snapshot และผลต่างที่อยู่ใต้รอบนั้น ไม่ลบสินค้า คลัง โลเคชั่น หรือบัญชีผู้ใช้</p><button className="btn danger" disabled={busy} onClick={resetTest}><Database size={15}/>ล้างข้อมูลทดสอบ</button></div></>}
 </Protected>
}
