'use client'
import {FormEvent,useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
const AUTH_DOMAIN='mbc.internal',UAT_PASSWORD_ALIAS='1234',UAT_AUTH_PASSWORD='MBC@1234'
export default function Login(){
 const[username,setUsername]=useState('admin');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const router=useRouter();const configured=useMemo(()=>Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY),[])
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');if(!configured){setError('ยังไม่ได้ตั้งค่า Supabase Environment Variables ใน Vercel');setBusy(false);return}const clean=username.trim().toLowerCase().replace(/\s+/g,'');if(!clean){setError('กรุณากรอกชื่อผู้ใช้');setBusy(false);return}const email=clean.includes('@')?clean:`${clean}@${AUTH_DOMAIN}`;const authPassword=password===UAT_PASSWORD_ALIAS?UAT_AUTH_PASSWORD:password;try{const{error}=await createClient().auth.signInWithPassword({email,password:authPassword});if(error)setError('เข้าสู่ระบบไม่สำเร็จ กรุณาตรวจสอบ Username และ Password');else{router.replace('/dashboard');router.refresh()}}catch{setError('เชื่อมต่อ Supabase ไม่สำเร็จ กรุณาตรวจสอบการตั้งค่าระบบ')}finally{setBusy(false)}}
 return <div className="login-page"><form className="login-card stack" onSubmit={submit}><div className="login-heading"><div className="login-mark">MBC</div><div><h1>Inventory Count</h1><div className="muted">ระบบตรวจนับสินค้าออนไลน์</div></div></div>{error&&<div className="error-box">{error}</div>}<div className="field"><label>ชื่อผู้ใช้</label><input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" placeholder="เช่น admin หรือ counter01" required/></div><div className="field"><label>รหัสผ่าน</label><div className="password-wrap"><input value={password} onChange={e=>setPassword(e.target.value)} type={showPassword?'text':'password'} autoComplete="current-password" placeholder="กรอกรหัสผ่าน" required/><button type="button" className="password-toggle" onClick={()=>setShowPassword(v=>!v)}>{showPassword?'ซ่อน':'แสดง'}</button></div></div><button className="btn primary" style={{minHeight:46,fontSize:15}} disabled={busy}>{busy?'กำลังเข้าสู่ระบบ...':'เข้าสู่ระบบ'}</button><div className="login-help">กรอกเฉพาะชื่อผู้ใช้ ไม่ต้องใส่ @mbc.internal</div></form></div>
}
