'use client'
import {ChangeEvent,FormEvent,useEffect,useMemo,useRef,useState} from 'react'
import {Boxes,Download,Edit3,PackagePlus,Search,Upload,X} from 'lucide-react'
import Protected from '@/components/Protected'
import {createClient} from '@/lib/supabase/client'
import {conditionLabel,conditionOptions} from '@/lib/constants'
import {exportXlsx,parseSpreadsheet} from '@/lib/export'
import {useProfile} from '@/lib/useProfile'
import type {Location,Product,StockCondition} from '@/lib/types'

type ProductRow=Product&{inventory_balances?:{quantity:number;condition:StockCondition;location_id:string;locations:any}[]}
const emptyForm={id:'',sku:'',name:'',brand:'',category:'',unit:'ชิ้น',cost:0,photo_url:'',notes:'',barcode:'',active:true}

export default function Products(){
 const s=useMemo(()=>createClient(),[]);const{profile}=useProfile();const canManage=!!profile&&['admin','warehouse_manager','sale_support'].includes(profile.role)
 const[rows,setRows]=useState<ProductRow[]>([]);const[locations,setLocations]=useState<Location[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[brand,setBrand]=useState('all');const[category,setCategory]=useState('all');const[open,setOpen]=useState(false);const[stockOpen,setStockOpen]=useState<ProductRow|null>(null);const[form,setForm]=useState(emptyForm);const[stock,setStock]=useState({location_id:'',condition:'good' as StockCondition,quantity:0});const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const fileRef=useRef<HTMLInputElement>(null)
 async function load(){setLoading(true);const[{data:p,error:e1},{data:l,error:e2}]=await Promise.all([s.from('products').select('*,product_barcodes(id,barcode,is_primary),inventory_balances(quantity,condition,location_id,locations(code,name,warehouses(code,name)))').order('sku'),s.from('locations').select('*,warehouses(code,name)').eq('active',true).order('code')]);if(e1||e2)setError(e1?.message||e2?.message||'โหลดข้อมูลไม่สำเร็จ');setRows((p||[]) as ProductRow[]);setLocations((l||[]) as Location[]);if(!stock.location_id&&l?.[0])setStock(v=>({...v,location_id:l[0].id}));setLoading(false)}
 useEffect(()=>{load()},[])
 function newProduct(){setForm(emptyForm);setOpen(true)}
 function editProduct(row:ProductRow){setForm({id:row.id,sku:row.sku,name:row.name,brand:row.brand||'',category:row.category||'',unit:row.unit||'ชิ้น',cost:Number(row.cost||0),photo_url:row.photo_url||'',notes:row.notes||'',barcode:row.product_barcodes?.find(x=>x.is_primary)?.barcode||row.product_barcodes?.[0]?.barcode||'',active:row.active});setOpen(true)}
 function balanceQuantity(row:ProductRow,locationId:string,condition:StockCondition){return Number(row.inventory_balances?.find(x=>x.location_id===locationId&&x.condition===condition)?.quantity||0)}
 function openStock(row:ProductRow){const first=row.inventory_balances?.[0];const locationId=first?.location_id||locations[0]?.id||'';const selectedCondition=first?.condition||'good';setStock({location_id:locationId,condition:selectedCondition,quantity:balanceQuantity(row,locationId,selectedCondition)});setStockOpen(row)}
 function changeStockArea(locationId:string,selectedCondition:StockCondition){setStock(v=>({...v,location_id:locationId,condition:selectedCondition,quantity:stockOpen?balanceQuantity(stockOpen,locationId,selectedCondition):0}))}
 async function saveProduct(e:FormEvent){e.preventDefault();setBusy(true);setError('');const barcode=form.barcode.trim();let barcodeOwner:{id:string;product_id:string}|null=null;if(barcode){const{data:owner,error:ownerError}=await s.from('product_barcodes').select('id,product_id').eq('barcode',barcode).maybeSingle();if(ownerError){setError(ownerError.message);setBusy(false);return}barcodeOwner=owner;if(owner&&owner.product_id!==form.id){setError(`บาร์โค้ด ${barcode} ถูกผูกกับสินค้าอื่นแล้ว`);setBusy(false);return}}
  const payload={sku:form.sku.trim().toUpperCase(),name:form.name.trim(),brand:form.brand.trim(),category:form.category.trim(),unit:form.unit.trim()||'ชิ้น',cost:Number(form.cost)||0,photo_url:form.photo_url.trim()||null,notes:form.notes.trim(),active:form.active,updated_at:new Date().toISOString()};let productId=form.id;if(form.id){const{error}=await s.from('products').update(payload).eq('id',form.id);if(error){setError(error.message);setBusy(false);return}}else{const{data,error}=await s.from('products').insert(payload).select('id').single();if(error){setError(error.message);setBusy(false);return}productId=data.id}
  if(barcode){const existing=rows.find(x=>x.id===productId)?.product_barcodes?.find(x=>x.is_primary)||rows.find(x=>x.id===productId)?.product_barcodes?.[0];if(barcodeOwner){const{error:demoteError}=await s.from('product_barcodes').update({is_primary:false}).eq('product_id',productId);if(demoteError){setError(demoteError.message);setBusy(false);return}const{error}=await s.from('product_barcodes').update({is_primary:true}).eq('id',barcodeOwner.id);if(error){setError(error.message);setBusy(false);return}}else if(existing){const{error}=await s.from('product_barcodes').update({barcode,is_primary:true}).eq('id',existing.id);if(error){setError(error.message);setBusy(false);return}}else{const{error}=await s.from('product_barcodes').insert({product_id:productId,barcode,is_primary:true});if(error){setError(error.message);setBusy(false);return}}}
  setMessage('บันทึกข้อมูลสินค้าเรียบร้อยแล้ว');setOpen(false);setBusy(false);load()}
 async function saveStock(e:FormEvent){e.preventDefault();if(!stockOpen)return;setBusy(true);const{data:{user}}=await s.auth.getUser();const{error}=await s.from('inventory_balances').upsert({product_id:stockOpen.id,location_id:stock.location_id,condition:stock.condition,quantity:Math.max(0,Math.floor(stock.quantity)),updated_at:new Date().toISOString(),updated_by:user?.id||null},{onConflict:'product_id,location_id,condition'});if(error)setError(error.message);else{setMessage('บันทึกยอดตามระบบแล้ว');setStockOpen(null);load()}setBusy(false)}
 async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');setMessage('กำลังนำเข้าข้อมูล...');try{const data=await parseSpreadsheet(file);let ok=0;const errors:string[]=[];for(const [index,row] of data.entries())try{const sku=text(row,['SKU','sku','รหัสสินค้า']);const name=text(row,['ชื่อสินค้า','Name','name','สินค้า']);if(!sku||!name)throw new Error('ไม่มี SKU หรือชื่อสินค้า');const productPayload={sku:sku.toUpperCase(),name,brand:text(row,['แบรนด์','Brand','brand']),category:text(row,['หมวดหมู่','Category','category']),unit:text(row,['หน่วย','Unit','unit'])||'ชิ้น',cost:num(row,['ต้นทุน','Cost','cost']),notes:text(row,['หมายเหตุ','Notes','notes']),active:true,updated_at:new Date().toISOString()};const{data:p,error}=await s.from('products').upsert(productPayload,{onConflict:'sku'}).select('id').single();if(error)throw error;const barcode=text(row,['บาร์โค้ด','Barcode','barcode','EAN']);if(barcode){const{data:owner,error:ownerError}=await s.from('product_barcodes').select('id,product_id').eq('barcode',barcode).maybeSingle();if(ownerError)throw ownerError;if(owner&&owner.product_id!==p.id)throw new Error(`บาร์โค้ด ${barcode} ถูกผูกกับสินค้าอื่นแล้ว`);if(owner){const{error:d}=await s.from('product_barcodes').update({is_primary:false}).eq('product_id',p.id);if(d)throw d;const{error:b}=await s.from('product_barcodes').update({is_primary:true}).eq('id',owner.id);if(b)throw b}else{const{error:b}=await s.from('product_barcodes').insert({product_id:p.id,barcode,is_primary:true});if(b)throw b}}const locCode=text(row,['โลเคชั่น','Location','location','Location Code']);const qtyValue=value(row,['จำนวน','Quantity','quantity','Qty']);if(locCode&&qtyValue!==''){const loc=locations.find(x=>x.code.toLowerCase()===locCode.toLowerCase());if(!loc)throw new Error(`ไม่พบโลเคชั่น ${locCode}`);const cond=normalizeCondition(text(row,['สภาพ','Condition','condition']));const{error:bal}=await s.from('inventory_balances').upsert({product_id:p.id,location_id:loc.id,condition:cond,quantity:Math.max(0,Math.floor(Number(qtyValue)||0))},{onConflict:'product_id,location_id,condition'});if(bal)throw bal}ok++}catch(err){errors.push(`แถว ${index+2}: ${err instanceof Error?err.message:'ผิดพลาด'}`)}setMessage(`นำเข้าสำเร็จ ${ok} แถว${errors.length?` · ไม่สำเร็จ ${errors.length} แถว`:''}`);if(errors.length)setError(errors.slice(0,8).join(' | '));await load()}catch(err){setError(err instanceof Error?err.message:'อ่านไฟล์ไม่สำเร็จ')}finally{setBusy(false);if(fileRef.current)fileRef.current.value=''}}
 async function exportProducts(){await exportXlsx(rows.map(x=>({'SKU':x.sku,'บาร์โค้ด':x.product_barcodes?.find(b=>b.is_primary)?.barcode||x.product_barcodes?.[0]?.barcode||'','ชื่อสินค้า':x.name,'แบรนด์':x.brand,'หมวดหมู่':x.category,'หน่วย':x.unit,'ต้นทุน':x.cost,'ยอดรวมตามระบบ':(x.inventory_balances||[]).reduce((n,b)=>n+Number(b.quantity),0),'สถานะ':x.active?'ใช้งาน':'ปิดใช้งาน'})),'MBC_Product_Master.xlsx','สินค้า')}
 const brands=[...new Set(rows.map(x=>x.brand).filter(Boolean))].sort();const categories=[...new Set(rows.map(x=>x.category).filter(Boolean))].sort();const filtered=rows.filter(x=>{const q=search.toLowerCase();return(brand==='all'||x.brand===brand)&&(category==='all'||x.category===category)&&(`${x.sku} ${x.name} ${x.brand} ${x.product_barcodes?.map(b=>b.barcode).join(' ')}`.toLowerCase().includes(q))})
 return <Protected>
  <div className="page-head"><div><h1>ข้อมูลสินค้า</h1><p>จัดการ SKU บาร์โค้ด แบรนด์ หมวดหมู่ และยอดตามระบบแยกโลเคชั่น</p></div>{canManage&&<div className="actions"><input ref={fileRef} className="hidden" type="file" accept=".xlsx,.xls,.csv" onChange={importFile}/><a className="btn outline" href="/product-import-template.csv" download>ดาวน์โหลด Template</a><button className="btn outline" disabled={busy} onClick={()=>fileRef.current?.click()}><Upload size={15}/>นำเข้า Excel</button><button className="btn primary" onClick={newProduct}><PackagePlus size={16}/>เพิ่มสินค้า</button></div>}</div>
  {error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}{message&&<div className="success-box" style={{marginBottom:12}}>{message}</div>}
  <div className="toolbar"><div className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหา SKU บาร์โค้ด ชื่อสินค้า หรือแบรนด์"/></div><div className="actions"><div className="field"><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="all">ทุกแบรนด์</option>{brands.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">ทุกหมวดหมู่</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div><button className="btn outline" onClick={exportProducts}><Download size={15}/>ส่งออก</button></div></div>
  <div className="table-wrap"><table className="table"><thead><tr><th>SKU / บาร์โค้ด</th><th>สินค้า</th><th>แบรนด์</th><th>หมวดหมู่</th><th>ยอดรวม</th><th>พร้อมขาย</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="empty">กำลังโหลด...</td></tr>:filtered.length?filtered.map(x=>{const total=(x.inventory_balances||[]).reduce((n,b)=>n+Number(b.quantity),0);const sell=(x.inventory_balances||[]).filter(b=>b.condition==='good').reduce((n,b)=>n+Number(b.quantity),0);return <tr key={x.id}><td><strong>{x.sku}</strong><div className="muted">{x.product_barcodes?.find(b=>b.is_primary)?.barcode||x.product_barcodes?.[0]?.barcode||'-'}</div></td><td className="wrap"><strong>{x.name}</strong><div className="muted">หน่วย {x.unit} · ต้นทุน {Number(x.cost||0).toLocaleString('th-TH',{minimumFractionDigits:2})}</div></td><td>{x.brand||'-'}</td><td>{x.category||'-'}</td><td><strong>{total.toLocaleString()}</strong></td><td className="diff-pos"><strong>{sell.toLocaleString()}</strong></td><td><span className={`badge ${x.active?'ok':'dark'}`}>{x.active?'ใช้งาน':'ปิดใช้งาน'}</span></td><td>{canManage&&<div className="actions"><button className="btn small secondary" onClick={()=>openStock(x)}><Boxes size={13}/>ตั้งยอด</button><button className="icon-button" title="แก้ไข" onClick={()=>editProduct(x)}><Edit3 size={14}/></button></div>}</td></tr>}):<tr><td colSpan={8} className="empty">ไม่พบข้อมูลสินค้า</td></tr>}</tbody></table></div>
  {open&&<div className="modal-backdrop"><form className="modal" onSubmit={saveProduct}><div className="modal-header"><h2>{form.id?'แก้ไขสินค้า':'เพิ่มสินค้า'}</h2><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="form-grid"><div className="field"><label>SKU *</label><input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} required/></div><div className="field"><label>บาร์โค้ดหลัก *</label><input value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})} required/></div><div className="field full"><label>ชื่อสินค้า *</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div className="field"><label>แบรนด์</label><input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></div><div className="field"><label>หมวดหมู่</label><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><div className="field"><label>หน่วยนับ</label><input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></div><div className="field"><label>ราคาทุน</label><input type="number" min={0} step="0.01" value={form.cost} onChange={e=>setForm({...form,cost:Number(e.target.value)})}/></div><div className="field full"><label>URL รูปสินค้า</label><input value={form.photo_url} onChange={e=>setForm({...form,photo_url:e.target.value})} placeholder="https://..."/></div><div className="field full"><label>หมายเหตุ</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><label className="checkbox full"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>เปิดใช้งานสินค้า</label></div><div className="modal-footer"><button type="button" className="btn outline" onClick={()=>setOpen(false)}>ยกเลิก</button><button className="btn primary" disabled={busy}>บันทึก</button></div></form></div>}
  {stockOpen&&<div className="modal-backdrop"><form className="modal" style={{width:'min(620px,100%)'}} onSubmit={saveStock}><div className="modal-header"><h2>ตั้งยอดตามระบบ</h2><button type="button" className="icon-button" onClick={()=>setStockOpen(null)}><X size={18}/></button></div><div className="notice" style={{marginBottom:13}}><strong>{stockOpen.sku}</strong> · {stockOpen.name}<br/>ยอดนี้จะถูกใช้เป็นยอดตามระบบและถูกเก็บ Snapshot เมื่อเริ่มรอบตรวจนับ</div><div className="form-grid"><div className="field full"><label>คลัง / โลเคชั่น</label><select value={stock.location_id} onChange={e=>changeStockArea(e.target.value,stock.condition)}>{locations.map(x=><option key={x.id} value={x.id}>{x.warehouses?.name} · {x.code} · {x.name}</option>)}</select></div><div className="field"><label>สภาพสินค้า</label><select value={stock.condition} onChange={e=>changeStockArea(stock.location_id,e.target.value as StockCondition)}>{conditionOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></div><div className="field"><label>จำนวนตามระบบ</label><input type="number" min={0} value={stock.quantity} onChange={e=>setStock({...stock,quantity:Number(e.target.value)||0})}/></div></div><div className="card" style={{marginTop:13,boxShadow:'none'}}><div className="card-title"><h3>ยอดที่มีอยู่</h3></div>{stockOpen.inventory_balances?.length?stockOpen.inventory_balances.map((b,i)=><div className="location-row" key={i}><div className="location-code">{b.locations?.code}</div><div className="location-copy"><strong>{b.locations?.warehouses?.name} · {b.locations?.name}</strong><span>{conditionLabel(b.condition)}</span></div><strong>{Number(b.quantity).toLocaleString()} {stockOpen.unit}</strong></div>):<div className="empty">ยังไม่มียอดตั้งต้น</div>}</div><div className="modal-footer"><button type="button" className="btn outline" onClick={()=>setStockOpen(null)}>ปิด</button><button className="btn primary" disabled={busy}>บันทึกยอด</button></div></form></div>}
 </Protected>
}
function value(row:Record<string,unknown>,keys:string[]){for(const key of keys)if(row[key]!==undefined&&row[key]!==null)return row[key];return ''}
function text(row:Record<string,unknown>,keys:string[]){return String(value(row,keys)||'').trim()}
function num(row:Record<string,unknown>,keys:string[]){return Number(value(row,keys))||0}
function normalizeCondition(input:string):StockCondition{const x=input.trim().toLowerCase();const hit=conditionOptions.find(o=>o.value===x||o.label.toLowerCase()===x||o.short.toLowerCase()===x);return hit?.value||'good'}
