'use client'
import {useEffect,useMemo,useState} from 'react'
import {AlertCircle,Download,Link2,RefreshCw,Search} from 'lucide-react'
import Protected from '@/components/Protected'
import {createClient} from '@/lib/supabase/client'
import {conditionLabel,statusLabel} from '@/lib/constants'
import {exportXlsx} from '@/lib/export'
import type {CountRound,Product} from '@/lib/types'

type Variance={round_id:string;product_id:string;sku:string;product_name:string;brand:string;category:string;unit:string;location_id:string;location_code:string;location_name:string;warehouse_name:string;condition:string;system_quantity:number;counted_quantity:number;difference:number}
type Unknown={id:string;barcode:string;quantity:number;condition:string;status:string;locations:any;first_seen_at:string}

export default function Variance(){
 const s=useMemo(()=>createClient(),[]);const[rounds,setRounds]=useState<CountRound[]>([]);const[roundId,setRoundId]=useState('');const[rows,setRows]=useState<Variance[]>([]);const[unknown,setUnknown]=useState<Unknown[]>([]);const[products,setProducts]=useState<Product[]>([])
 const[search,setSearch]=useState('');const[status,setStatus]=useState('all');const[brand,setBrand]=useState('all');const[condition,setCondition]=useState('all');const[tab,setTab]=useState<'variance'|'unknown'>('variance');const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');const[error,setError]=useState('')
 async function loadBase(){const[{data:r},{data:p}]=await Promise.all([s.from('count_rounds').select('*,warehouses(code,name)').in('status',['active','review','approved']).order('created_at',{ascending:false}),s.from('products').select('id,sku,name,brand,category,unit,cost,photo_url,notes,active,product_barcodes(barcode,is_primary)').eq('active',true).order('sku')]);const rs=(r||[]) as CountRound[];setRounds(rs);const requested=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('round')||'':'';if(requested&&rs.some(x=>x.id===requested))setRoundId(requested);setProducts((p||[]) as Product[]);if(!roundId&&!requested&&rs[0])setRoundId(rs[0].id)}
 async function load(){if(!roundId){setRows([]);setUnknown([]);setLoading(false);return}setLoading(true);setError('');const[{data:v,error:e1},{data:u,error:e2}]=await Promise.all([s.from('v_round_variance').select('*').eq('round_id',roundId).order('brand').order('sku'),s.from('unknown_barcodes').select('id,barcode,quantity,condition,status,first_seen_at,locations(code,name,warehouses(code,name))').eq('round_id',roundId).order('updated_at',{ascending:false})]);if(e1||e2)setError(e1?.message||e2?.message||'โหลดข้อมูลไม่สำเร็จ');setRows((v||[]) as Variance[]);setUnknown((u||[]) as Unknown[]);setLoading(false)}
 useEffect(()=>{loadBase()},[]);useEffect(()=>{load()},[roundId])
 const brands=[...new Set(rows.map(x=>x.brand).filter(Boolean))].sort()
 const filtered=rows.filter(x=>{const q=search.toLowerCase();const state=status==='all'||(status==='short'&&Number(x.difference)<0)||(status==='over'&&Number(x.difference)>0)||(status==='equal'&&Number(x.difference)===0)||(status==='uncounted'&&Number(x.counted_quantity)===0&&Number(x.system_quantity)>0);return state&&(brand==='all'||x.brand===brand)&&(condition==='all'||x.condition===condition)&&(`${x.sku} ${x.product_name} ${x.brand} ${x.location_code}`.toLowerCase().includes(q))})
 const summary=filtered.reduce((a,x)=>{a.system+=Number(x.system_quantity);a.counted+=Number(x.counted_quantity);if(x.difference<0)a.short+=Math.abs(Number(x.difference));if(x.difference>0)a.over+=Number(x.difference);return a},{system:0,counted:0,short:0,over:0})
 async function exportReport(){await exportXlsx(filtered.map(x=>({'SKU':x.sku,'สินค้า':x.product_name,'แบรนด์':x.brand,'คลัง':x.warehouse_name,'โลเคชั่น':`${x.location_code} ${x.location_name}`,'สภาพ':conditionLabel(x.condition),'ยอดตามระบบ':x.system_quantity,'นับจริง':x.counted_quantity,'ผลต่าง':x.difference,'หน่วย':x.unit})),'MBC_Stock_Variance.xlsx','ผลต่างสต๊อก')}
 async function resolveUnknown(item:Unknown){const sku=window.prompt(`ระบุ SKU ที่ต้องการผูกกับบาร์โค้ด ${item.barcode}`);if(!sku)return;const product=products.find(p=>p.sku.toLowerCase()===sku.trim().toLowerCase());if(!product)return setError('ไม่พบ SKU ที่ระบุ');if(!window.confirm(`ผูกบาร์โค้ด ${item.barcode} กับ ${product.sku} · ${product.name} หรือไม่?`))return;setError('');const{data:owner,error:ownerError}=await s.from('product_barcodes').select('product_id').eq('barcode',item.barcode).maybeSingle();if(ownerError){setError(ownerError.message);return}if(owner&&owner.product_id!==product.id){setError('บาร์โค้ดนี้ถูกผูกกับสินค้าอื่นแล้ว กรุณาตรวจสอบก่อนแก้ไข');return}if(!owner){const{error:barcodeError}=await s.from('product_barcodes').insert({product_id:product.id,barcode:item.barcode,is_primary:false});if(barcodeError){setError(barcodeError.message);return}}const{data:{user}}=await s.auth.getUser();const{error}=await s.from('unknown_barcodes').update({status:'linked',resolved_product_id:product.id,resolved_by:user?.id||null,resolved_at:new Date().toISOString(),resolution_note:`ผูกกับ ${product.sku}`}).eq('id',item.id);if(error)setError(error.message);else{setMessage('ผูกบาร์โค้ดกับสินค้าเรียบร้อยแล้ว รายการสแกนเดิมยังคงอยู่ในประวัติและควรนับสินค้านี้ใหม่');load()}}
 async function ignoreUnknown(item:Unknown){const note=window.prompt('เหตุผลที่ข้ามบาร์โค้ดนี้','ไม่ใช่สินค้าคงคลัง');if(!note)return;const{data:{user}}=await s.auth.getUser();const{error}=await s.from('unknown_barcodes').update({status:'ignored',resolved_by:user?.id||null,resolved_at:new Date().toISOString(),resolution_note:note}).eq('id',item.id);if(error)setError(error.message);else{setMessage('ข้ามรายการแล้ว');load()}}
 const current=rounds.find(x=>x.id===roundId)
 return <Protected>
  <div className="page-head"><div><h1>ผลต่างสต๊อก</h1><p>เปรียบเทียบ Snapshot ยอดตามระบบกับยอดตรวจนับจริงก่อนอนุมัติ</p></div><div className="actions"><button className="btn outline" onClick={load}><RefreshCw size={15}/>รีเฟรช</button><button className="btn primary" onClick={exportReport} disabled={!filtered.length}><Download size={15}/>ส่งออก Excel</button></div></div>
  {error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}{message&&<div className="success-box" style={{marginBottom:12}}>{message}</div>}
  <div className="filters" style={{gridTemplateColumns:'minmax(220px,2fr) repeat(3,minmax(130px,1fr))'}}><div className="field"><label>รอบตรวจนับ</label><select value={roundId} onChange={e=>setRoundId(e.target.value)}><option value="">เลือกรอบ</option>{rounds.map(r=><option key={r.id} value={r.id}>{r.code} · {r.name} · {statusLabel(r.status)}</option>)}</select></div><div className="field"><label>แบรนด์</label><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="all">ทุกแบรนด์</option>{brands.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>สภาพสินค้า</label><select value={condition} onChange={e=>setCondition(e.target.value)}><option value="all">ทุกสภาพ</option>{[...new Set(rows.map(x=>x.condition))].map(x=><option key={x} value={x}>{conditionLabel(x)}</option>)}</select></div><div className="field"><label>สถานะผลต่าง</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">ทั้งหมด</option><option value="short">จำนวนขาด</option><option value="over">จำนวนเกิน</option><option value="equal">จำนวนตรง</option><option value="uncounted">ยังไม่ได้นับ</option></select></div></div>
  <div className="grid kpi-grid"><Summary label="ยอดตามระบบ" value={summary.system}/><Summary label="ยอดนับจริง" value={summary.counted} tone="good"/><Summary label="จำนวนขาด" value={summary.short} tone="bad"/><Summary label="จำนวนเกิน" value={summary.over} tone="warn"/></div>
  <div className="tabs"><button className={`tab ${tab==='variance'?'active':''}`} onClick={()=>setTab('variance')}>ผลต่างสินค้า ({rows.length})</button><button className={`tab ${tab==='unknown'?'active':''}`} onClick={()=>setTab('unknown')}>บาร์โค้ดไม่พบ ({unknown.filter(x=>x.status==='open').length})</button></div>
  {tab==='variance'?<div className="card"><div className="toolbar"><div className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหา SKU ชื่อสินค้า แบรนด์ หรือโลเคชั่น"/></div><div className="stat-strip"><div className="stat-pill">รอบ <strong>{current?.code||'-'}</strong></div><div className="stat-pill">รายการ <strong>{filtered.length}</strong></div></div></div><div className="table-wrap"><table className="table"><thead><tr><th>SKU / สินค้า</th><th>แบรนด์</th><th>คลัง / โลเคชั่น</th><th>สภาพ</th><th>ตามระบบ</th><th>นับจริง</th><th>ผลต่าง</th><th>สถานะ</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="empty">กำลังโหลด...</td></tr>:filtered.length?filtered.map(x=><tr key={`${x.product_id}-${x.location_id}-${x.condition}`}><td className="wrap"><strong>{x.sku}</strong><div className="muted">{x.product_name}</div></td><td>{x.brand||'-'}</td><td>{x.warehouse_name}<div className="muted">{x.location_code} · {x.location_name}</div></td><td><span className="badge dark">{conditionLabel(x.condition)}</span></td><td>{Number(x.system_quantity).toLocaleString()}</td><td>{Number(x.counted_quantity).toLocaleString()}</td><td className={x.difference>0?'diff-pos':x.difference<0?'diff-neg':'diff-zero'}>{x.difference>0?'+':''}{Number(x.difference).toLocaleString()}</td><td><VarianceBadge x={x}/></td></tr>):<tr><td colSpan={8} className="empty">ไม่พบรายการตามตัวกรอง</td></tr>}</tbody></table></div></div>:
  <div className="card"><div className="notice" style={{marginBottom:13,display:'flex',gap:8,alignItems:'center'}}><AlertCircle size={16}/><span>การผูกบาร์โค้ดจะใช้กับการยิงครั้งถัดไป รายการเดิมที่ยิงไม่พบจะไม่ถูกย้ายเป็นยอดสินค้าอัตโนมัติเพื่อรักษาประวัติ</span></div><div className="table-wrap"><table className="table"><thead><tr><th>บาร์โค้ด</th><th>คลัง / โลเคชั่น</th><th>สภาพ</th><th>จำนวน</th><th>พบครั้งแรก</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{unknown.length?unknown.map(x=><tr key={x.id}><td><strong>{x.barcode}</strong></td><td>{x.locations?.warehouses?.name||'-'} / {x.locations?.code||'-'}</td><td>{conditionLabel(x.condition)}</td><td>{Number(x.quantity).toLocaleString()}</td><td>{new Date(x.first_seen_at).toLocaleString('th-TH')}</td><td><span className={`badge ${x.status==='open'?'bad':x.status==='linked'?'ok':'dark'}`}>{x.status==='open'?'รอตรวจสอบ':x.status==='linked'?'ผูกแล้ว':'ข้ามแล้ว'}</span></td><td>{x.status==='open'&&<div className="actions"><button className="btn small secondary" onClick={()=>resolveUnknown(x)}><Link2 size={13}/>ผูกสินค้า</button><button className="btn small outline" onClick={()=>ignoreUnknown(x)}>ข้าม</button></div>}</td></tr>):<tr><td colSpan={7} className="empty">ไม่มีบาร์โค้ดไม่พบในรอบนี้</td></tr>}</tbody></table></div></div>}
 </Protected>
}
function Summary({label,value,tone='' }:{label:string;value:number;tone?:string}){return <div className={`kpi-card ${tone}`}><div className="kpi-label">{label}</div><div className="kpi-value">{value.toLocaleString()}</div><div className="kpi-sub">ตามรายการที่กรอง</div></div>}
function VarianceBadge({x}:{x:Variance}){if(x.counted_quantity===0&&x.system_quantity>0)return <span className="badge bad">ยังไม่ได้นับ</span>;if(x.difference<0)return <span className="badge bad">จำนวนขาด</span>;if(x.difference>0)return <span className="badge warn">จำนวนเกิน</span>;return <span className="badge ok">จำนวนตรง</span>}
