'use client'
import {FormEvent,useEffect,useRef,useState} from 'react'
import Protected from '@/components/Protected'
import {createClient} from '@/lib/supabase/client'
import type {CountRound,Location} from '@/lib/types'
import {enqueueScan,getQueue,saveQueue,type QueuedScan} from '@/lib/offlineQueue'
type Recent={id:string;barcode:string;sku:string;product_name:string;quantity_delta:number;created_at:string}
export default function Scan(){const s=createClient();const input=useRef<HTMLInputElement>(null);const[rounds,setRounds]=useState<CountRound[]>([]);const[locations,setLocations]=useState<Location[]>([]);const[roundId,setRoundId]=useState('');const[locationId,setLocationId]=useState('');const[condition,setCondition]=useState('good');const[qty,setQty]=useState(1);const[barcode,setBarcode]=useState('');const[msg,setMsg]=useState('');const[recent,setRecent]=useState<Recent[]>([]);const[total,setTotal]=useState(0);const[pending,setPending]=useState(0)
async function load(){setPending(getQueue().length);const [{data:r},{data:l}]=await Promise.all([s.from('count_rounds').select('*').eq('status','active').order('created_at',{ascending:false}),s.from('locations').select('*').eq('active',true).order('code')]);setRounds((r||[]) as CountRound[]);setLocations((l||[]) as Location[]);if(r?.[0])setRoundId(r[0].id);if(l?.[0])setLocationId(l[0].id)}
async function loadRecent(){if(!roundId)return;const{data}=await s.from('scan_events').select('id,barcode,quantity_delta,created_at,products(sku,name)').eq('round_id',roundId).order('created_at',{ascending:false}).limit(12);setRecent((data||[]).map((x:any)=>({id:x.id,barcode:x.barcode,quantity_delta:x.quantity_delta,created_at:x.created_at,sku:x.products?.sku||'UNKNOWN',product_name:x.products?.name||'ไม่พบสินค้า'})));const{data:t}=await s.from('scan_totals').select('quantity').eq('round_id',roundId);setTotal(((t||[]) as Array<{quantity:number|string|null}>).reduce((n:number,x:{quantity:number|string|null})=>n+Number(x.quantity||0),0))}
useEffect(()=>{load()},[]);useEffect(()=>{loadRecent();if(!roundId)return;const ch=s.channel('scan-'+roundId).on('postgres_changes',{event:'*',schema:'public',table:'scan_totals',filter:`round_id=eq.${roundId}`},()=>loadRecent()).subscribe();return()=>{s.removeChannel(ch)}},[roundId])
async function submit(e:FormEvent){e.preventDefault();if(!roundId||!locationId||!barcode.trim())return;setMsg('กำลังบันทึก...');const payload:QueuedScan={p_round_id:roundId,p_location_id:locationId,p_condition:condition,p_barcode:barcode.trim(),p_quantity:qty,p_client_event_id:crypto.randomUUID(),p_device_id:localStorage.getItem('mbc_device_id'),queued_at:new Date().toISOString()};const{data,error}=await s.rpc('record_scan',payload);if(error){enqueueScan(payload);setPending(getQueue().length);setMsg('อินเทอร์เน็ตหรือระบบขัดข้อง: เก็บไว้รอซิงก์แล้ว')}else{const r=(data as any)?.[0];setMsg(r?.is_unknown?'บันทึกบาร์โค้ดไม่พบแล้ว':'บันทึกสำเร็จ: '+(r?.sku||barcode));await loadRecent()}setBarcode('');input.current?.focus()}
async function syncQueue(){const q=getQueue();if(!q.length)return;setMsg('กำลังซิงก์ '+q.length+' รายการ...');const remain:QueuedScan[]=[];for(const item of q){const{error}=await s.rpc('record_scan',item);if(error)remain.push(item)}saveQueue(remain);setPending(remain.length);setMsg(remain.length?'ยังซิงก์ไม่ได้ '+remain.length+' รายการ':'ซิงก์รายการค้างครบแล้ว');await loadRecent()}
async function undo(id:string){const reason=prompt('เหตุผลที่ย้อนรายการ','ยิงผิด');if(!reason)return;const{error}=await s.rpc('undo_scan',{p_scan_event_id:id,p_reason:reason,p_client_event_id:crypto.randomUUID()});setMsg(error?'ย้อนรายการไม่สำเร็จ: '+error.message:'ย้อนรายการแล้ว');loadRecent()}
return <Protected><div className="topbar"><div><div className="page-title">ยิงบาร์โค้ด</div><div className="muted">ยอดรวมทันทีหลัง Supabase ยืนยัน</div></div><div style={{display:'flex',gap:8,alignItems:'center'}}><div className="badge">ยอดในรอบ {total}</div><button className="btn secondary" onClick={syncQueue}>รอซิงก์ {pending}</button></div></div><div className="card"><form className="stack" onSubmit={submit}><div className="form-row"><div className="field"><label>รอบตรวจนับ</label><select value={roundId} onChange={e=>setRoundId(e.target.value)}>{rounds.map(x=><option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></div><div className="field"><label>โลเคชั่น</label><select value={locationId} onChange={e=>setLocationId(e.target.value)}>{locations.map(x=><option key={x.id} value={x.id}>{x.code} - {x.name}</option>)}</select></div><div className="field"><label>สภาพสินค้า</label><select value={condition} onChange={e=>setCondition(e.target.value)}><option value="good">ปกติ</option><option value="damaged">เสียหาย</option><option value="demo">DEMO</option></select></div><div className="field"><label>จำนวนต่อครั้ง</label><input type="number" min="1" max="10000" value={qty} onChange={e=>setQty(Number(e.target.value))}/></div></div><div className="scan-box"><input ref={input} className="scan-input" autoFocus placeholder="ยิงหรือกรอกบาร์โค้ด" value={barcode} onChange={e=>setBarcode(e.target.value)}/><button className="btn primary">บันทึก</button></div>{msg&&<div className={msg.includes('ผิด')?'error':'ok'}>{msg}</div>}</form></div><div className="card" style={{marginTop:16}}><h3>รายการล่าสุด</h3><div className="table-wrap"><table className="table"><thead><tr><th>เวลา</th><th>SKU</th><th>สินค้า</th><th>บาร์โค้ด</th><th>จำนวน</th><th></th></tr></thead><tbody>{recent.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleTimeString('th-TH')}</td><td>{x.sku}</td><td>{x.product_name}</td><td>{x.barcode}</td><td>{x.quantity_delta}</td><td>{x.quantity_delta>0&&<button className="btn danger" onClick={()=>undo(x.id)}>ย้อนรายการ</button>}</td></tr>)}</tbody></table></div></div></Protected>}
