'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {Ban,CheckCircle2,ClipboardCheck,Play,Plus,Search,Send,SlidersHorizontal,X} from 'lucide-react'
import Protected from '@/components/Protected'
import {createClient} from '@/lib/supabase/client'
import {statusLabel} from '@/lib/constants'
import type {CountRound,Warehouse} from '@/lib/types'
import {useProfile} from '@/lib/useProfile'

type RoundRow=CountRound&{warehouses?:{code:string;name:string};v_round_progress?:unknown}
type ProgressRow={round_id:string;expected_lines:number;counted_lines:number;progress_percent:number;counted_quantity:number}

export default function Rounds(){
 const s=useMemo(()=>createClient(),[]);const{profile}=useProfile();const canManage=!!profile&&['admin','warehouse_manager','sale_support'].includes(profile.role);const[rows,setRows]=useState<RoundRow[]>([]);const[warehouses,setWarehouses]=useState<Warehouse[]>([]);const[progress,setProgress]=useState<Record<string,ProgressRow>>({})
 const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const[search,setSearch]=useState('');const[statusFilter,setStatusFilter]=useState('all')
 const[form,setForm]=useState({code:'',name:'',warehouse_id:'',planned_start:new Date().toISOString().slice(0,10),environment:'production',notes:'',blind_count:false})
 async function load(){setError('');const[{data:r,error:e1},{data:w,error:e2},{data:p}]=await Promise.all([s.from('count_rounds').select('*,warehouses(code,name)').order('created_at',{ascending:false}),s.from('warehouses').select('*').eq('active',true).order('code'),s.from('v_round_progress').select('*')]);if(e1||e2){setError(e1?.message||e2?.message||'โหลดข้อมูลไม่สำเร็จ');return}setRows((r||[]) as RoundRow[]);setWarehouses((w||[]) as Warehouse[]);const map:Record<string,ProgressRow>={};for(const x of p||[])map[x.round_id]=x as ProgressRow;setProgress(map);if(!form.warehouse_id&&w?.[0])setForm(v=>({...v,warehouse_id:w[0].id}))}
 useEffect(()=>{load()},[])
 async function createRound(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');const{data:{user}}=await s.auth.getUser();if(!user){setError('Session หมดอายุ กรุณา Login ใหม่');setBusy(false);return}const payload={...form,code:form.code.trim().toUpperCase(),name:form.name.trim(),created_by:user.id,status:'draft'};const{error}=await s.from('count_rounds').insert(payload);if(error)setError(error.message);else{setMessage('สร้างรอบตรวจนับเรียบร้อยแล้ว');setOpen(false);setForm(v=>({...v,code:'',name:'',notes:'',blind_count:false}));await load()}setBusy(false)}
 async function changeStatus(row:RoundRow,next:'active'|'review'|'approved'|'cancelled'){let reason:string|null=null;if(next==='cancelled'){reason=window.prompt('กรุณาระบุเหตุผลที่ยกเลิกรอบตรวจนับ','ยกเลิกรอบตรวจนับ');if(!reason)return}if(next==='approved'&&!window.confirm('อนุมัติผลตรวจนับและสร้างรายการปรับสต๊อกหรือไม่? ยังไม่ปรับยอดจริงจนกว่าจะกด “ปรับยอดสต๊อก”'))return;setBusy(true);const{error}=await s.rpc('set_round_status',{p_round_id:row.id,p_status:next,p_reason:reason});if(error)setError(error.message);else setMessage(`เปลี่ยนสถานะเป็น ${statusLabel(next)} แล้ว`);setBusy(false);load()}
 async function applyAdjustments(row:RoundRow){if(!window.confirm('ยืนยันปรับยอดสต๊อกตามผลตรวจนับที่อนุมัติแล้ว? การดำเนินการนี้จะเปลี่ยนยอดตามระบบ'))return;setBusy(true);const{data,error}=await s.rpc('apply_round_adjustments',{p_round_id:row.id});if(error)setError(error.message);else setMessage(`ปรับยอดสต๊อกสำเร็จ ${data||0} รายการ`);setBusy(false);load()}
 const filtered=rows.filter(r=>{const q=search.toLowerCase();return(statusFilter==='all'||r.status===statusFilter)&&(`${r.code} ${r.name} ${r.warehouses?.name||''}`.toLowerCase().includes(q))})
 return <Protected>
  <div className="page-head"><div><h1>รอบตรวจนับ</h1><p>สร้าง ควบคุมสถานะ ตรวจสอบ และอนุมัติผลก่อนปรับยอดสต๊อก</p></div>{canManage&&<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={16}/>สร้างรอบใหม่</button>}</div>
  {error&&<div className="error-box" style={{marginBottom:12}}>{error}</div>}{message&&<div className="success-box" style={{marginBottom:12}}>{message}</div>}
  <div className="toolbar"><div className="search-box"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหารหัสรอบ ชื่อรอบ หรือคลัง"/></div><div className="actions"><div className="field" style={{minWidth:170}}><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">ทุกสถานะ</option><option value="draft">แบบร่าง</option><option value="active">กำลังตรวจนับ</option><option value="review">รอตรวจสอบ</option><option value="approved">อนุมัติแล้ว</option><option value="cancelled">ยกเลิก</option></select></div><a href="/variance" className="btn outline"><SlidersHorizontal size={15}/>ดูผลต่าง</a></div></div>
  <div className="table-wrap"><table className="table"><thead><tr><th>รหัสรอบ</th><th>รายละเอียด</th><th>คลัง</th><th>วันที่เริ่ม</th><th>ความคืบหน้า</th><th>สถานะ</th><th>การดำเนินการ</th></tr></thead><tbody>{filtered.length?filtered.map(row=>{const p=progress[row.id];const pct=Number(p?.progress_percent||0);return <tr key={row.id}><td><strong>{row.code}</strong><div className="muted">{row.environment==='production'?'ใช้งานจริง':'ทดสอบ'}</div></td><td className="wrap"><strong>{row.name}</strong><div className="muted">{row.notes||'ไม่มีหมายเหตุ'}</div></td><td>{row.warehouses?.code} · {row.warehouses?.name}</td><td>{row.planned_start?new Date(row.planned_start).toLocaleDateString('th-TH'):'-'}</td><td style={{minWidth:160}}><div className="progress-meta"><span>{p?.counted_lines||0}/{p?.expected_lines||0} รายการ</span><b>{pct.toFixed(0)}%</b></div><div className="progress"><span style={{width:`${Math.min(100,pct)}%`}}/></div></td><td><StatusBadge status={row.status}/>{row.adjustments_applied_at&&<div className="muted" style={{marginTop:4}}>ปรับยอดแล้ว</div>}</td><td><div className="actions">
       {canManage&&row.status==='draft'&&<button className="btn small primary" disabled={busy} onClick={()=>changeStatus(row,'active')}><Play size={13}/>เริ่มนับ</button>}
       {row.status==='active'&&<><a href={`/scan?round=${row.id}`} className="btn small secondary"><ClipboardCheck size={13}/>เปิดนับ</a>{canManage&&<button className="btn small warning" disabled={busy} onClick={()=>changeStatus(row,'review')}><Send size={13}/>ส่งตรวจ</button>}</>}
       {row.status==='review'&&<><a href={`/variance?round=${row.id}`} className="btn small secondary">ตรวจผลต่าง</a>{canManage&&<button className="btn small success" disabled={busy} onClick={()=>changeStatus(row,'approved')}><CheckCircle2 size={13}/>อนุมัติ</button>}</>}
       {canManage&&row.status==='approved'&&!row.adjustments_applied_at&&<button className="btn small dark" disabled={busy} onClick={()=>applyAdjustments(row)}>ปรับยอดสต๊อก</button>}
       {canManage&&['draft','active','review'].includes(row.status)&&<button className="icon-button" title="ยกเลิก" disabled={busy} onClick={()=>changeStatus(row,'cancelled')}><Ban size={14}/></button>}
      </div></td></tr>}):<tr><td colSpan={7} className="empty">ไม่พบรอบตรวจนับ</td></tr>}</tbody></table></div>
  {open&&<div className="modal-backdrop"><form className="modal" onSubmit={createRound}><div className="modal-header"><h2>สร้างรอบตรวจนับใหม่</h2><button type="button" className="icon-button" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="form-grid">
   <div className="field"><label>รหัสรอบ *</label><input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="เช่น COUNT-AUG-2026" required/></div>
   <div className="field"><label>วันที่เริ่มตามแผน</label><input type="date" value={form.planned_start} onChange={e=>setForm({...form,planned_start:e.target.value})}/></div>
   <div className="field full"><label>ชื่อรอบตรวจนับ *</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="เช่น ตรวจนับประจำเดือน สิงหาคม 2026" required/></div>
   <div className="field"><label>คลังสินค้า *</label><select value={form.warehouse_id} onChange={e=>setForm({...form,warehouse_id:e.target.value})} required><option value="">เลือกคลัง</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></div>
   <div className="field"><label>ประเภทข้อมูล</label><select value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}><option value="production">ใช้งานจริง</option><option value="test">ทดสอบระบบ</option></select></div>
   <div className="field full"><label>หมายเหตุ</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="ขอบเขตหรือคำแนะนำสำหรับผู้ตรวจนับ"/></div>
   <label className="checkbox full"><input type="checkbox" checked={form.blind_count} onChange={e=>setForm({...form,blind_count:e.target.checked})}/><span>Blind Count — ซ่อนยอดตามระบบจากผู้ตรวจนับ</span></label>
  </div><div className="notice" style={{marginTop:13}}>เมื่อกด “เริ่มนับ” ระบบจะเก็บ Snapshot ยอดตามระบบของคลังนี้ เพื่อใช้เปรียบเทียบผลต่างโดยไม่เปลี่ยนตามยอดภายหลัง</div><div className="modal-footer"><button type="button" className="btn outline" onClick={()=>setOpen(false)}>ยกเลิก</button><button className="btn primary" disabled={busy}>บันทึกรอบตรวจนับ</button></div></form></div>}
 </Protected>
}

function StatusBadge({status}:{status:string}){const cls=status==='active'?'live':status==='approved'?'ok':status==='review'?'warn':status==='cancelled'?'bad':'dark';return <span className={`badge ${cls}`}>{statusLabel(status)}</span>}
